// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Embed API (embed/v1)
// Description:
//   Provides the ability to embed various Bloombox data in 3rd party apps and
//   websites.

#import <GoogleApiClientForRest/GTLRObject.h>

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLREmbed_DedData;

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLREmbed.EmbeddedMenuStyle

/** Value: "MASTER_DETAIL" */
GTLR_EXTERN NSString * const kGTLREmbed_EmbeddedMenuStyle_MasterDetail;
/** Value: "MASTER_ONLY" */
GTLR_EXTERN NSString * const kGTLREmbed_EmbeddedMenuStyle_MasterOnly;

/**
 *  GTLREmbed_DedData
 */
@interface GTLREmbed_DedData : GTLRObject

@property(nonatomic, copy, nullable) NSString *environment;
@property(nonatomic, copy, nullable) NSString *link;

@end


/**
 *  GTLREmbed_DedViewSpec
 */
@interface GTLREmbed_DedViewSpec : GTLRObject

@property(nonatomic, copy, nullable) NSString *location;
@property(nonatomic, copy, nullable) NSString *partner;
@property(nonatomic, strong, nullable) GTLREmbed_DedData *payload;
@property(nonatomic, copy, nullable) NSString *script;
@property(nonatomic, copy, nullable) NSString *style;

@end

NS_ASSUME_NONNULL_END
