// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Embed API (embed/v1)
// Description:
//   Provides the ability to embed various Bloombox data in 3rd party apps and
//   websites.

#import "GTLREmbedObjects.h"
#import "GTLREmbedQuery.h"
#import "GTLREmbedService.h"
