/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-04-23 at 19:31:11 UTC 
 * Modify at your own risk.
 */

package io.bloombox.bloombox.client.EmbedAPI.model;

/**
 * Model definition for EmbeddedViewSpec.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Embed API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EmbeddedViewSpec extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String partner;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private EmbeddedData payload;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String script;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String style;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public EmbeddedViewSpec setLocation(java.lang.String location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPartner() {
    return partner;
  }

  /**
   * @param partner partner or {@code null} for none
   */
  public EmbeddedViewSpec setPartner(java.lang.String partner) {
    this.partner = partner;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public EmbeddedData getPayload() {
    return payload;
  }

  /**
   * @param payload payload or {@code null} for none
   */
  public EmbeddedViewSpec setPayload(EmbeddedData payload) {
    this.payload = payload;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getScript() {
    return script;
  }

  /**
   * @param script script or {@code null} for none
   */
  public EmbeddedViewSpec setScript(java.lang.String script) {
    this.script = script;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStyle() {
    return style;
  }

  /**
   * @param style style or {@code null} for none
   */
  public EmbeddedViewSpec setStyle(java.lang.String style) {
    this.style = style;
    return this;
  }

  @Override
  public EmbeddedViewSpec set(String fieldName, Object value) {
    return (EmbeddedViewSpec) super.set(fieldName, value);
  }

  @Override
  public EmbeddedViewSpec clone() {
    return (EmbeddedViewSpec) super.clone();
  }

}
