// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Embed API (embed/v1)
// Description:
//   Provides the ability to embed various Bloombox data in 3rd party apps and
//   websites.

#import "GTLRBBEmbedObjects.h"
#import "GTLRBBEmbedQuery.h"
#import "GTLRBBEmbedService.h"
