// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   Embed API (embed/v1)
// Description:
//   Provides the ability to embed various Bloombox data in 3rd party apps and
//   websites.

#import "GTLRBBEmbedObjects.h"

// ----------------------------------------------------------------------------
// Constants

// GTLRBBEmbed.EmbeddedMenuStyle
NSString * const kGTLRBBEmbed_EmbeddedMenuStyle_MasterDetail = @"MASTER_DETAIL";
NSString * const kGTLRBBEmbed_EmbeddedMenuStyle_MasterOnly   = @"MASTER_ONLY";

// ----------------------------------------------------------------------------
//
//   GTLRBBEmbed_EmbeddedData
//

@implementation GTLRBBEmbed_EmbeddedData
@dynamic environment, link;
@end


// ----------------------------------------------------------------------------
//
//   GTLRBBEmbed_EmbeddedViewSpec
//

@implementation GTLRBBEmbed_EmbeddedViewSpec
@dynamic location, partner, payload, script, style;
@end
