/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-04-23 at 19:30:56 UTC 
 * Modify at your own risk.
 */

package io.bloombox.bloombox.client.EmbedAPI;

/**
 * Service definition for EmbedAPI (v1).
 *
 * <p>
 * Provides the ability to embed various Bloombox data in 3rd party apps and websites.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EmbedAPIRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class EmbedAPI extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the Embed API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://bloombox-io.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "embed/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public EmbedAPI(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  EmbedAPI(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "data".
   *
   * This request holds the parameters needed by the embed server.  After setting any optional
   * parameters, call the {@link Data#execute()} method to invoke the remote operation.
   *
   * @param partner
   * @param location
   * @return the request
   */
  public Data data(java.lang.String partner, java.lang.String location) throws java.io.IOException {
    Data result = new Data(partner, location);
    initialize(result);
    return result;
  }

  public class Data extends EmbedAPIRequest<io.bloombox.bloombox.client.EmbedAPI.model.EmbeddedData> {

    private static final String REST_PATH = "{partner}/{location}/data";

    /**
     * Create a request for the method "data".
     *
     * This request holds the parameters needed by the the embed server.  After setting any optional
     * parameters, call the {@link Data#execute()} method to invoke the remote operation. <p> {@link
     * Data#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param partner
     * @param location
     * @since 1.13
     */
    protected Data(java.lang.String partner, java.lang.String location) {
      super(EmbedAPI.this, "GET", REST_PATH, null, io.bloombox.bloombox.client.EmbedAPI.model.EmbeddedData.class);
      this.partner = com.google.api.client.util.Preconditions.checkNotNull(partner, "Required parameter partner must be specified.");
      this.location = com.google.api.client.util.Preconditions.checkNotNull(location, "Required parameter location must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Data setAlt(java.lang.String alt) {
      return (Data) super.setAlt(alt);
    }

    @Override
    public Data setFields(java.lang.String fields) {
      return (Data) super.setFields(fields);
    }

    @Override
    public Data setKey(java.lang.String key) {
      return (Data) super.setKey(key);
    }

    @Override
    public Data setOauthToken(java.lang.String oauthToken) {
      return (Data) super.setOauthToken(oauthToken);
    }

    @Override
    public Data setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Data) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Data setQuotaUser(java.lang.String quotaUser) {
      return (Data) super.setQuotaUser(quotaUser);
    }

    @Override
    public Data setUserIp(java.lang.String userIp) {
      return (Data) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String partner;

    /**

     */
    public java.lang.String getPartner() {
      return partner;
    }

    public Data setPartner(java.lang.String partner) {
      this.partner = partner;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String location;

    /**

     */
    public java.lang.String getLocation() {
      return location;
    }

    public Data setLocation(java.lang.String location) {
      this.location = location;
      return this;
    }

    @Override
    public Data set(String parameterName, Object value) {
      return (Data) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "view".
   *
   * This request holds the parameters needed by the embed server.  After setting any optional
   * parameters, call the {@link View#execute()} method to invoke the remote operation.
   *
   * @param partner
   * @param location
   * @param style
   * @return the request
   */
  public View view(java.lang.String partner, java.lang.String location, java.lang.String style) throws java.io.IOException {
    View result = new View(partner, location, style);
    initialize(result);
    return result;
  }

  public class View extends EmbedAPIRequest<io.bloombox.bloombox.client.EmbedAPI.model.EmbeddedViewSpec> {

    private static final String REST_PATH = "{partner}/{location}/view/{style}";

    /**
     * Create a request for the method "view".
     *
     * This request holds the parameters needed by the the embed server.  After setting any optional
     * parameters, call the {@link View#execute()} method to invoke the remote operation. <p> {@link
     * View#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must be
     * called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param partner
     * @param location
     * @param style
     * @since 1.13
     */
    protected View(java.lang.String partner, java.lang.String location, java.lang.String style) {
      super(EmbedAPI.this, "GET", REST_PATH, null, io.bloombox.bloombox.client.EmbedAPI.model.EmbeddedViewSpec.class);
      this.partner = com.google.api.client.util.Preconditions.checkNotNull(partner, "Required parameter partner must be specified.");
      this.location = com.google.api.client.util.Preconditions.checkNotNull(location, "Required parameter location must be specified.");
      this.style = com.google.api.client.util.Preconditions.checkNotNull(style, "Required parameter style must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public View setAlt(java.lang.String alt) {
      return (View) super.setAlt(alt);
    }

    @Override
    public View setFields(java.lang.String fields) {
      return (View) super.setFields(fields);
    }

    @Override
    public View setKey(java.lang.String key) {
      return (View) super.setKey(key);
    }

    @Override
    public View setOauthToken(java.lang.String oauthToken) {
      return (View) super.setOauthToken(oauthToken);
    }

    @Override
    public View setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (View) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public View setQuotaUser(java.lang.String quotaUser) {
      return (View) super.setQuotaUser(quotaUser);
    }

    @Override
    public View setUserIp(java.lang.String userIp) {
      return (View) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String partner;

    /**

     */
    public java.lang.String getPartner() {
      return partner;
    }

    public View setPartner(java.lang.String partner) {
      this.partner = partner;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String location;

    /**

     */
    public java.lang.String getLocation() {
      return location;
    }

    public View setLocation(java.lang.String location) {
      this.location = location;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String style;

    /**

     */
    public java.lang.String getStyle() {
      return style;
    }

    public View setStyle(java.lang.String style) {
      this.style = style;
      return this;
    }

    @Override
    public View set(String parameterName, Object value) {
      return (View) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link EmbedAPI}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link EmbedAPI}. */
    @Override
    public EmbedAPI build() {
      return new EmbedAPI(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EmbedAPIRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEmbedAPIRequestInitializer(
        EmbedAPIRequestInitializer embedapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(embedapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
